package ch.lu.mygym.supersetservice;


import ch.lu.mygym.dtos.entities.RoutineEntity;
import ch.lu.mygym.dtos.plain.ExerciseGroupDTO;
import ch.lu.mygym.dtos.plain.SetDTO;
import ch.lu.mygym.exerciseservice.ExerciseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Collections;
import java.util.List;

@Controller
@RestController
@RequestMapping("/routine-service")
public class ExerciseGroupService {

    @Autowired  //This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GroupRepository groupRepository;

    @CrossOrigin // (origins = "http://localhost:4200")
    @GetMapping(value="/get-json-routines", produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public Iterable<ExerciseGroupDTO> getPropertyJSON() {

        List<RoutineEntity> routines = groupRepository.findAll();
        List<ExerciseGroupDTO> exerciseGroups = ExerciseGroupConverter.convertGroupEntitiesToDTO(routines);

        return exerciseGroups;
    }


}
