package ch.lu.mygym.exerciseservice;

import ch.lu.mygym.dtos.plain.ExerciseDTO;
import ch.lu.mygym.dtos.plain.ExerciseSetContainerDTO;
import ch.lu.mygym.dtos.plain.ExerciseSetDTO;
import com.google.gson.Gson;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


import java.util.List;
import java.util.stream.Collectors;

@Controller
@RestController
@RequestMapping("/exercise")
public class ExerciseService {
    @Autowired  //This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ExerciseRepository exerciseRepository;

    @CrossOrigin // (origins = "http://localhost:4200")
    @GetMapping(value="/get-sets", produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public Iterable<ExerciseDTO> getPropertyJSON(@RequestParam(defaultValue="") List<Integer> exerciseIds) {
        // Add the user to parameter list and consider by reading from db
        ExerciseSetConverter exerciseSetConverter = new ExerciseSetConverter();
        System.out.println(exerciseIds);
        return exerciseIds.stream().map(a -> exerciseSetConverter.createPseudoExerciseDTO(a, exerciseRepository.getAllSetsOf(a, 1))).collect(Collectors.toList());
    }
}
