package ch.lu.mygym.workoutservice;



import ch.lu.mygym.dtos.entities.UserEntity;
import ch.lu.mygym.dtos.plain.ExerciseGroupDTO;

import ch.lu.mygym.dtos.plain.UserDTO;
import ch.lu.mygym.dtos.plain.WorkoutDTO;
import ch.lu.mygym.loginservice.UserRepository;
import ch.lu.mygym.supersetservice.GroupRepository;
import com.google.gson.Gson;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@RestController
@RequestMapping("/workout-service")
public class WorkoutService {

    @Autowired  //This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GroupRepository groupRepository;

    @Autowired
    private UserRepository userRepository;



    @CrossOrigin // (origins = "http://localhost:4200")
    @PostMapping(value="/get-workouts",
            produces = MediaType.APPLICATION_JSON_VALUE,
            consumes = MediaType.APPLICATION_JSON_VALUE
    )
    @ResponseBody
    public Iterable<WorkoutDTO> getPropertyJSON(@RequestBody UserDTO user) {

        System.out.println("check");

        UserEntity userEntity = userRepository.findById(user.getId());
List<WorkoutDTO> workoutDTOs = WorkoutConverter.convertWorkoutEntitiesToDTO(userEntity.getWorkoutEntities());

        return workoutDTOs;
    }
/*
@PostMapping(value = "/save",
            consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE
    )
    @ResponseBody
    public String getPropertyJSON(@RequestBody String exercise) {
 */

}
class UserId {
    private int id;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
